
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "afadffcc2ba239504a1d6f452eac4f7a33b3db65",
 "version": "1.2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
