
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-21T10:59:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ee91021d577c2e9b4f2c62ccb3395e290b2df85",
 "version": "1.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
